### ISSUE TITLE
Research: Design Backend Infrastructure

### ISSUE THREAD

**Issue by cwarren279** [Developer-DUCS/eMission#18]
Talk with Sigman to gain access to the mcs Drury server. Though anyone can help with this task, this is a job that will be led by the Server Manager. Once the server is up, we'll need to discuss and design our backend. (Nodejs might be our only option).

**Comment by jalikat3** [comment]
I started doing the Medium tutorial i posted in the discord. I'm going to make a new branch and put it there, since there are still some aspects of it not working (at least showing red underlines).
