### ISSUE TITLE
Complete Emission Research

### ISSUE THREAD

**Issue by Jhutchinson98** [Developer-DUCS/eMission#4]
Choose an API to collect the carbon emission data

**Comment by cwarren279** [comment]
Option 1:

Climatiq
https://www.climatiq.io/

**Comment by cwarren279** [comment]
Option 2:

Carbon Interface
 - Vehicle CO2 Estimates (easily calculate co2 emissions estimates from driving)

https://www.carboninterface.com/vehicles
