### ISSUE TITLE
Research: Flutter Unit Testing

### ISSUE THREAD

**Issue by cwarren279** [Developer-DUCS/eMission#50]
Begin researching and implementing some basic tests for the flutter application. 

Start Here: 

* https://docs.flutter.dev/testing

* https://docs.flutter.dev/cookbook/testing/unit/introduction

**Comment by jalikat3** [comment]
One thing that can be tested already is insertUser. Might go back and utilize a User model class to create the user, so that it's easier to mock this class and test things such as 1. what if the user doesn't enter a field? 2. test for general success and failure behavior
