### ISSUE TITLE
Task: Build Application Structure

### ISSUE THREAD

**Issue by Jhutchinson98** [Developer-DUCS/eMission#7]
Create flutter application structure using figma prototype screens as a template

- This Task will be made up of a collection of smaller features, each of which will need to be completed before this issue can be closed. 

[Figma Prototype](https://www.figma.com/file/9cRrTzi2Tw4IY18ZF5N0BR/Prototype-(Copy)?type=design&node-id=0-1&mode=design&t=yqbdSAhBesD8sHPI-0) 

**To Get Started**
1.  clone eMission repo 
2.  checkout 'code_sample'
3.  begin coding (have fun)

**Comment by cwarren279** [comment]
[Feature 1](https://github.com/Developer-DUCS/eMission/issues/9)

[Feature 1 again]
